apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-udfr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-udfr
    app.kubernetes.io/part-of: ci1t-830-0043-app
  name: devfile-sample-udfr
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-udfr
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-udfr
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0043-tenant/ci1t-830-0043-app/devfile-sample-udfr@sha256:5bb870005cddcbfa2e3a4b1af9f29cf590b3dccd350d73b1db5da178b8b424ba
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
